# Generated by Django 4.1 on 2022-09-13 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_module_submodule_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_fa_icon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='sub_module_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.submodule'),
        ),
    ]
