# Generated by Django 4.1 on 2022-09-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_account_name_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
