# Generated by Django 4.1 on 2022-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_alter_account_user_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='profile/avatar.png', null=True, upload_to='profile'),
        ),
    ]
